### ISSUE TITLE
Wie kann ich die create_charts.py Datei nutzen?

### ISSUE THREAD

**Issue by Minkafighter** [FrederikP/isp-peering-performance-logger#1]
Hi,

Ich habe deinen [Reddit Post](https://www.reddit.com/r/help/comments/awx61y/reddit_image_hosting_extremely_slow_in_germany/?st=jukbkz6k&sh=d589f84d) gefunden und wollte meine Verbindung ebenfalls aufzeichnen.

Das script zum Downloaden funktioniert und downloadet bei mir alle 10 minuten, so wie es soll, die Dateien und schreibt die Zeiten dann in eine log datei.

Wenn ich jedoch die create_charts.py datei ausführe, bekomme ich folgenden error:

```
root@vpn:~/graph# sudo python ./create_charts_bokeh.py
Traceback (most recent call last):
  File "./create_charts_bokeh.py", line 106, in <module>
    create_chart('hetzner')
  File "./create_charts_bokeh.py", line 96, in create_chart
    chart.legend[0].plot = None
  File "/usr/local/lib/python3.6/dist-packages/bokeh/core/has_props.py", line 288, in __setattr__
    (name, self.__class__.__name__, text, nice_join(matches)))
AttributeError: unexpected attribute 'plot' to Legend, possible attributes are background_fill_alpha, background_fill_color, border_line_alpha, border_line_cap, border_line_color, border_line_dash, border_line_dash_offset, border_line_join, border_line_width, click_policy, glyph_height, glyph_width, inactive_fill_alpha, inactive_fill_color, items, js_event_callbacks, js_property_callbacks, label_height, label_standoff, label_text_align, label_text_alpha, label_text_baseline, label_text_color, label_text_font, label_text_font_size, label_text_font_style, label_text_line_height, label_width, level, location, margin, name, orientation, padding, spacing, subscribed_events, tags or visible

root@vpn:~/graph# ls
create_charts_bokeh.py  hetzner.log  home.log

root@vpn:~/graph#

```
bokeh und pandas sind installiert, als python version versuchte ich die neueste 3.7 und 3.6 version.

Wäre schön wenn du mir dabei helfen könntest.

Mfg

**Comment by FrederikP** [comment]
Hi, vllt hat sich was mit der neuen bokeh Version (1.1.0) geändert. Du kannst es ja mal mit der vorversion probieren. Ich schau es mir mal bei Gelegenheit an.

**Comment by FrederikP** [comment]
Ja mit version 1.1.0 kommt der fehler bei mir auch. probier mal version 1.0.4 
ich schau mal ob ichs auch mit version 1.1.0 easy hinbekomme

**Comment by FrederikP** [comment]
I changed the script so it works with bokeh 1.1.0. Please try again
